/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.buenosaries.vistas;

import entidades.User;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.buenosaries.vistas//Mantenedores//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MantenedoresTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.buenosaries.vistas.MantenedoresTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_MantenedoresAction",
        preferredID = "MantenedoresTopComponent"
)
@Messages({
    "CTL_MantenedoresAction=Mantenedores",
    "CTL_MantenedoresTopComponent=Mantenedores Window",
    "HINT_MantenedoresTopComponent=Esta es la ventana Mantenedores"
})
public final class MantenedoresTopComponent extends TopComponent implements ExplorerManager.Provider {
    
    private static ExplorerManager em = new ExplorerManager();
    
    public MantenedoresTopComponent() {
        initComponents();
        setName(Bundle.CTL_MantenedoresTopComponent());
        setToolTipText(Bundle.HINT_MantenedoresTopComponent());
        
        /*
        EntityManager entityManager = Persistence.createEntityManagerFactory("BuenosAiresPU").createEntityManager();
        Query query = entityManager.createNamedQuery("User.findAll");
        List<User> resultList = query.getResultList();
        
        em.setRootContext(new AbstractNode(Children.create(new UserNodeFactory(resultList), true)));
        */
        refreshNode();
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        //for (User u : resultList) {
        //    jTextArea1.append(u.getUsername() + " (" + u.getPassword() + ")" + "\n");
        //}
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beanTreeView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beanTreeView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }
    
    public static void refreshNode() {
    EntityManager entityManager = Persistence.createEntityManagerFactory("BuenosAiresPU").createEntityManager();
    Query query = entityManager.createNamedQuery("User.findAll");
    List<User> resultList = query.getResultList();
    em.setRootContext(new UserRootNode(Children.create(new UserNodeFactory(resultList), true)));
} 
    
 
}
